# Generated by Django 4.1 on 2022-09-04 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('atention', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Meta_device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('serie', models.CharField(max_length=20)),
                ('date_adquisicion', models.DateTimeField(verbose_name='fecha en que se registró')),
                ('date_retiro', models.DateTimeField(verbose_name='fecha en que se retiró')),
                ('area_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.area')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MAÑ', 'MAÑANA'), ('TAR', 'TARDE'), ('NOC', 'NOCHE'), ('SPE', 'ESPECIAL'), ('OTR', 'OTRO')], max_length=20)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('day', models.ManyToManyField(to='objects.day')),
            ],
        ),
        migrations.CreateModel(
            name='Device_extern',
            fields=[
                ('meta_device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.meta_device')),
                ('uses', models.SmallIntegerField(default=0)),
            ],
            bases=('objects.meta_device',),
        ),
        migrations.CreateModel(
            name='Device_intern',
            fields=[
                ('meta_device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='objects.meta_device')),
                ('id_label', models.CharField(max_length=7, unique=True)),
                ('status', models.CharField(max_length=10)),
                ('maintenance', models.SmallIntegerField(default=0)),
                ('area_de_uso', models.CharField(max_length=20)),
                ('date_mantenimiento', models.DateTimeField(verbose_name='fecha del ultimo mantenimiento')),
            ],
            bases=('objects.meta_device',),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('Puesto', models.CharField(max_length=20)),
                ('Horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('Equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.device_extern')),
            ],
        ),
    ]
