# Generated by Django 4.1 on 2022-09-04 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Salida_interno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.device_intern')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.device_extern')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('atiende', models.CharField(max_length=100)),
                ('reponsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.worker')),
                ('reporta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.area')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=100)),
                ('evaluacion', models.CharField(max_length=100)),
                ('initial_state', models.CharField(max_length=100)),
                ('final_state', models.CharField(max_length=100)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.device_intern')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.reporte')),
            ],
        ),
    ]
